# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='children/photo', verbose_name='Фото')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'М'), (1, 'Ж')], verbose_name='Пол')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('room', models.CharField(max_length=10, verbose_name='Класс')),
                ('is_study', models.BooleanField(default=False, verbose_name='Учится или нет')),
            ],
            options={
                'verbose_name_plural': 'Дети',
                'verbose_name': 'Ребенок',
            },
        ),
    ]
