# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_type', models.PositiveSmallIntegerField(verbose_name='Кто привел/забрал')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время когда привели/забрали')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child')),
            ],
            options={
                'verbose_name': 'Запись журнала привода/забирания детей из сада',
                'verbose_name_plural': 'Записи журнала привода/забирания детей из сада',
            },
        ),
    ]
